### PR TITLE
auto detection of .ezmk files

### PR DESCRIPTION
**Pull request by coolcoy12**
had to include a standard libary

### CODE REVIEW

**Comment by MousieDev** [comment]
I dont think this is useful. Because if you have multiple .ezmk files, then it will select the first one and thats not expected..

**Comment by MousieDev** [comment]
I think it sould be system of use default or specify own.

**Comment by coolcoy12** [comment]
this is just a quick patch because people just want to type "easymake" and have it automatic find their file

**Comment by MousieDev** [comment]
Then they need to specify its name wtf

**Comment by coolcoy12** [comment]
no the point is that just say easymake and ill autofind and build the only part that you need to worry about is makeing the file

**Comment by WittySmirk** [comment]
We could make it so that if there are multiple .ezmk files it says not specific enough, but if there’s only one it will take that in regardless of the name

**Comment by undersquire** [comment]
Ill keep this open here for now until we figure out if we want this feature or not.

**Comment by coolcoy12** [comment]
i think we should also add what witty said

**Comment by coolcoy12** [comment]
added what witty said

**Comment by DynamicDonkey** [comment]
Closing the PR for now as it can't be merged cleanly. Will be discussed at a later date.

**Pull request closed without merging**
